### PR TITLE
added files i missed

### PR DESCRIPTION
**Pull request by ahmed-elsaharti**
Please use [PX4 Discuss](http://discuss.px4.io/) or [Slack](http://slack.px4.io/) to align on pull requests if necessary. You can then open draft pull requests to get early feedback.

## Describe problem solved by this pull request
A clear and concise description of the problem this proposed change will solve. Or, what it will improve.
E.g. For this use case I ran into...

## Describe your solution
A clear and concise description of what you have implemented.

## Describe possible alternatives
A clear and concise description of alternative solutions or features you've considered.

## Test data / coverage
How was it tested? What cases were covered? Logs uploaded to https://review.px4.io/ and screenshots of the important plot parts.

## Additional context
Add any other related context or media.

### CODE REVIEW

**Comment by jasonruen-thread** [comment]
@ahmed-elsaharti what issues should this PR be connected to?

**Comment by ahmed-elsaharti** [comment]
@jasonruen-thread this fills in files that i missed in the PR right before this one 😅😅

**Review by SoggyOtter — APPROVED** [review]
This is fine to add

**Comment by ahmed-elsaharti** [comment]
@aroller @jasonruen-thread  looks like i dont have write access to merge this PR :D

**Pull request merged**
